In [6]:
import torch
import numpy as np

###  torch.nonzero(input, out=None) → LongTensor

    Returns a tensor containing the indices of all non-zero elements of input. 
    
    Each row in the result contains the indices of a non-zero element in input.

    If input has n dimensions, then the resulting indices tensor out is of size (z×n)
     
    where z is the total number of non-zero elements in the input tensor.

In [7]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

#### input is 1 dimension, n =1, z = 4(because 4 nonzero numbers)
so output of this is 4*1

In [8]:
torch.nonzero(torch.tensor([[0.6, 3.0, 0.0, 0.0],
                                [0.0, 0.4, 0.0, 0.0],
                                [0.0, 0.0, 1.2, 0.0],
                                [0.0, 0.0, 0.0,-0.4]]))

tensor([[0, 0],
        [0, 1],
        [1, 1],
        [2, 2],
        [3, 3]])

In this case, z = 5, n = 2, that means output dimension is 
5*2

### When using torch.nonzero as mask
### Target: substract nonzero element from output,
### Consider a output:

output.size() = 20 * 5

The last colume is confidence of the row object, 

our target is substract those rows whose last colume value is lower than confidence

In [53]:
output = torch.Tensor(np.random.randn(20,5)*100)

In [54]:
output, output.size()

(tensor([[  48.5357, -146.0935,   21.4445,   88.1572, -163.6515],
         [ -11.6059, -202.5803, -272.6208,  -70.6494,   48.2462],
         [  32.2817,  143.3642,   65.2313,  204.4687,  -20.5622],
         [ 115.8655,  -98.2565, -212.8266,  143.0192,   57.0147],
         [-165.0712,   -6.6130,  -20.0685,  171.9330, -162.5612],
         [ -86.6402, -146.7946,   15.3071,   63.3969,  101.3253],
         [  15.3417,  -72.3814,  125.2183,  -61.0257,  -96.1000],
         [ -16.1364, -111.1410,  325.7547,  -34.7463,  -25.8186],
         [ -40.0351, -264.0844,  -92.2704,  131.7545,  -89.1409],
         [  76.0579,   51.4955,  -41.4646,  -15.0318,  282.0169],
         [ -50.3221, -102.9140,  -43.5693,  -96.9760,   -4.9674],
         [ 169.2142,  -39.2906,   -0.1051,   38.8216,   89.4203],
         [-112.4179,    5.2091,   -9.0554, -169.9529, -154.7604],
         [  50.7450,  -66.4929,  -58.3294,    0.8711, -151.0265],
         [-191.1933,  103.8244,   74.2020,  -96.9899,  251.0168],
         [

In [55]:
confidence = 20

In [56]:
mask_index = (output[:,4] > confidence).float()

In [57]:
mask_index, mask_index.size()

(tensor([0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1.,
         1., 1.]), torch.Size([20]))

In [58]:
mask_index = mask_index.unsqueeze(1)

### Now we get (20,1) confidence true or false

In [59]:
mask_index, mask_index.size()

(tensor([[0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [0.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [1.],
         [1.]]), torch.Size([20, 1]))

In [60]:
output = output * mask_index

### Make those lower than confidence row to all 0

In [61]:
output

tensor([[   0.0000,   -0.0000,    0.0000,    0.0000,   -0.0000],
        [ -11.6059, -202.5803, -272.6208,  -70.6494,   48.2462],
        [   0.0000,    0.0000,    0.0000,    0.0000,   -0.0000],
        [ 115.8655,  -98.2565, -212.8266,  143.0192,   57.0147],
        [  -0.0000,   -0.0000,   -0.0000,    0.0000,   -0.0000],
        [ -86.6402, -146.7946,   15.3071,   63.3969,  101.3253],
        [   0.0000,   -0.0000,    0.0000,   -0.0000,   -0.0000],
        [  -0.0000,   -0.0000,    0.0000,   -0.0000,   -0.0000],
        [  -0.0000,   -0.0000,   -0.0000,    0.0000,   -0.0000],
        [  76.0579,   51.4955,  -41.4646,  -15.0318,  282.0169],
        [  -0.0000,   -0.0000,   -0.0000,   -0.0000,   -0.0000],
        [ 169.2142,  -39.2906,   -0.1051,   38.8216,   89.4203],
        [  -0.0000,    0.0000,   -0.0000,   -0.0000,   -0.0000],
        [   0.0000,   -0.0000,   -0.0000,    0.0000,   -0.0000],
        [-191.1933,  103.8244,   74.2020,  -96.9899,  251.0168],
        [   0.0000,    0.

In [62]:
non_zero_idx = torch.nonzero(output[:,4])

### Get nonzero index of last colume

In [63]:
non_zero_idx

tensor([[ 1],
        [ 3],
        [ 5],
        [ 9],
        [11],
        [14],
        [17],
        [18],
        [19]])

In [64]:
output = output[non_zero_idx.squeeze(), :]

In [65]:
output, output.size()

(tensor([[ -11.6059, -202.5803, -272.6208,  -70.6494,   48.2462],
         [ 115.8655,  -98.2565, -212.8266,  143.0192,   57.0147],
         [ -86.6402, -146.7946,   15.3071,   63.3969,  101.3253],
         [  76.0579,   51.4955,  -41.4646,  -15.0318,  282.0169],
         [ 169.2142,  -39.2906,   -0.1051,   38.8216,   89.4203],
         [-191.1933,  103.8244,   74.2020,  -96.9899,  251.0168],
         [  43.9860,  -64.1296,  -69.0855,   93.3626,   71.4551],
         [  -7.6771,  -80.8006,  -64.2967,   -3.6101,   77.6459],
         [-227.5292,  -94.0063, -184.4980,  134.4211,   25.0151]]),
 torch.Size([9, 5]))