In [1]:
import torch

## tensor is like ndarray
torch.Tensor uninitialled random matrix

In [4]:
x = torch.Tensor(5,3)
print(x)


  -0.0000    0.0000   -0.0000
   0.0000    0.0000    0.0000
 127.0485    0.0000    0.0000
   0.0000    0.0000    0.0000
   0.0000    0.0000    0.0000
[torch.FloatTensor of size 5x3]



### initial  random matrix

In [3]:
x = torch.rand(5,3)
print(x)


 0.9824  0.7308  0.1925
 0.7534  0.6180  0.1837
 0.9227  0.0213  0.1356
 0.5116  0.1414  0.2359
 0.9578  0.9687  0.1271
[torch.FloatTensor of size 5x3]



### get size of tensor

In [7]:
x.size()

torch.Size([5, 3])

### Operation
Tensor operation can be written as torch.add(x,y), y.add_(x). All of them is equal to matrix operation, and can be automatically get derivation

In [10]:
y = torch.rand(5,3)
z = x + y
print(z)


   0.2823    0.7308    0.7491
   0.6747    0.4993    0.9699
 127.6645    0.1783    0.2293
   0.8971    0.2815    0.9831
   0.6375    0.5185    0.5707
[torch.FloatTensor of size 5x3]



### Convert tensor to numpy array

In [12]:
h = z.numpy()
print(h)

[[  0.28234303   0.73079073   0.74908525]
 [  0.67465603   0.4993267    0.9698655 ]
 [127.66448      0.17831641   0.22931135]
 [  0.8971106    0.28148293   0.9830894 ]
 [  0.6374865    0.51852226   0.57069737]]


### Still satisfy matrix broadcasting rule

In [13]:
print(z)
print(z+1)


   0.2823    0.7308    0.7491
   0.6747    0.4993    0.9699
 127.6645    0.1783    0.2293
   0.8971    0.2815    0.9831
   0.6375    0.5185    0.5707
[torch.FloatTensor of size 5x3]


   1.2823    1.7308    1.7491
   1.6747    1.4993    1.9699
 128.6645    1.1783    1.2293
   1.8971    1.2815    1.9831
   1.6375    1.5185    1.5707
[torch.FloatTensor of size 5x3]



### Can be move to GPU

In [16]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x+y)


   0.2823    0.7308    0.7491
   0.6747    0.4993    0.9699
 127.6645    0.1783    0.2293
   0.8971    0.2815    0.9831
   0.6375    0.5185    0.5707
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]

