In [3]:
import torch
import numpy as np

In [15]:
grid = np.arange(5)

In [27]:
a,b = np.meshgrid(grid,grid)
print(a,b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]] [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [17]:
x_offset = torch.FloatTensor(a).view(-1,1)

In [19]:
y_offset = torch.FloatTensor(b).view(-1,1)

In [24]:
x_offset, y_offset

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [0.],
         [1.],
         [2.],
         [3.],
         [4.]]), tensor([[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [3.],
         [3.],
         [3.],
         [3.],
         [3.],
         [4.],
         [4.],
         [4.],
         [4.],
         [4.]]))

In [22]:
cated = torch.cat((x_offset,y_offset),1)

In [23]:
cated

tensor([[0., 0.],
        [1., 0.],
        [2., 0.],
        [3., 0.],
        [4., 0.],
        [0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.],
        [4., 1.],
        [0., 2.],
        [1., 2.],
        [2., 2.],
        [3., 2.],
        [4., 2.],
        [0., 3.],
        [1., 3.],
        [2., 3.],
        [3., 3.],
        [4., 3.],
        [0., 4.],
        [1., 4.],
        [2., 4.],
        [3., 4.],
        [4., 4.]])

In [29]:
repeated = cated.repeat(1,3)

In [30]:
repeated

tensor([[0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 1., 0.],
        [2., 0., 2., 0., 2., 0.],
        [3., 0., 3., 0., 3., 0.],
        [4., 0., 4., 0., 4., 0.],
        [0., 1., 0., 1., 0., 1.],
        [1., 1., 1., 1., 1., 1.],
        [2., 1., 2., 1., 2., 1.],
        [3., 1., 3., 1., 3., 1.],
        [4., 1., 4., 1., 4., 1.],
        [0., 2., 0., 2., 0., 2.],
        [1., 2., 1., 2., 1., 2.],
        [2., 2., 2., 2., 2., 2.],
        [3., 2., 3., 2., 3., 2.],
        [4., 2., 4., 2., 4., 2.],
        [0., 3., 0., 3., 0., 3.],
        [1., 3., 1., 3., 1., 3.],
        [2., 3., 2., 3., 2., 3.],
        [3., 3., 3., 3., 3., 3.],
        [4., 3., 4., 3., 4., 3.],
        [0., 4., 0., 4., 0., 4.],
        [1., 4., 1., 4., 1., 4.],
        [2., 4., 2., 4., 2., 4.],
        [3., 4., 3., 4., 3., 4.],
        [4., 4., 4., 4., 4., 4.]])

In [32]:
viewed = repeated.view(-1,2)

In [33]:
viewed

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [2., 0.],
        [2., 0.],
        [2., 0.],
        [3., 0.],
        [3., 0.],
        [3., 0.],
        [4., 0.],
        [4., 0.],
        [4., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [2., 1.],
        [2., 1.],
        [2., 1.],
        [3., 1.],
        [3., 1.],
        [3., 1.],
        [4., 1.],
        [4., 1.],
        [4., 1.],
        [0., 2.],
        [0., 2.],
        [0., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [3., 2.],
        [3., 2.],
        [3., 2.],
        [4., 2.],
        [4., 2.],
        [4., 2.],
        [0., 3.],
        [0., 3.],
        [0., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [3., 3.],
        [3

In [34]:
viewed.unsqueeze(0)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [2., 0.],
         [2., 0.],
         [2., 0.],
         [3., 0.],
         [3., 0.],
         [3., 0.],
         [4., 0.],
         [4., 0.],
         [4., 0.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [2., 1.],
         [2., 1.],
         [2., 1.],
         [3., 1.],
         [3., 1.],
         [3., 1.],
         [4., 1.],
         [4., 1.],
         [4., 1.],
         [0., 2.],
         [0., 2.],
         [0., 2.],
         [1., 2.],
         [1., 2.],
         [1., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.],
         [3., 2.],
         [3., 2.],
         [3., 2.],
         [4., 2.],
         [4., 2.],
         [4., 2.],
         [0., 3.],
         [0., 3.],
         [0., 3.],
         [1., 3.],
         [1., 3.],
         [1., 3.],
         [2., 3.],
         [2.

In [35]:
anchors = [(13,14),(7,7),(35,36)]

In [36]:
anchors = torch.FloatTensor(anchors)

### .repeat(dim0_times, dim1_times)
__第一个参数__ 指在第0个维度重复5次
__第二个参数__ 指在第1个维度重复2次

In [40]:
anchors.repeat(5,2)

tensor([[13., 14., 13., 14.],
        [ 7.,  7.,  7.,  7.],
        [35., 36., 35., 36.],
        [13., 14., 13., 14.],
        [ 7.,  7.,  7.,  7.],
        [35., 36., 35., 36.],
        [13., 14., 13., 14.],
        [ 7.,  7.,  7.,  7.],
        [35., 36., 35., 36.],
        [13., 14., 13., 14.],
        [ 7.,  7.,  7.,  7.],
        [35., 36., 35., 36.],
        [13., 14., 13., 14.],
        [ 7.,  7.,  7.,  7.],
        [35., 36., 35., 36.]])

In [42]:
anchors.repeat(2,5)

tensor([[13., 14., 13., 14., 13., 14., 13., 14., 13., 14.],
        [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
        [35., 36., 35., 36., 35., 36., 35., 36., 35., 36.],
        [13., 14., 13., 14., 13., 14., 13., 14., 13., 14.],
        [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
        [35., 36., 35., 36., 35., 36., 35., 36., 35., 36.]])